INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (1, 1, 1, N'2019      ', N'180       ', N'manuel              ')
INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (2, 2, 2, N'2018      ', N'500       ', N'manuel              ')
INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (3, 3, 1, N'2018      ', N'300       ', N'manuel              ')
INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (4, 4, 3, N'2017      ', N'200       ', N'otomatik            ')
INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (5, 5, 1, N'2017      ', N'200       ', N'manuel              ')
INSERT INTO [dbo].[Cars] ([ProductId], [BrandId], [ColorId], [ModelYear], [DailyPrice], [Description]) VALUES (6, 6, 1, N'2020      ', N'180       ', NULL)
